# frozen_string_literal: true

require "digest"
require "fileutils"
require "net/http"
require "open3"
require "uri"

module Tfs
  # Prepares patched ruby source trees ("tfs-ruby-<version>-src"):
  # fetch the official tarball (sha256-verified, cached), extract it,
  # then apply the version's patch set with git apply.
  #
  # A selected patch whose target file does not exist in the pristine tree
  # (e.g. config.status, which is generated by ./configure) is DEFERRED
  # with a note on stderr -- the consumer applies it after configure.
  # Any other patch that fails to apply raises ApplyError (loud, named).
  class SourcePrep
    # Base error for every failure raised by SourcePrep.
    class Error < StandardError; end
    # Tarball bytes do not match the manifest sha256.
    class IntegrityError < Error; end
    # Tarball could not be downloaded.
    class DownloadError < Error; end
    # A patch failed git apply / git apply --check.
    class ApplyError < Error; end

    # One audit outcome: a patch checked against the pristine tree.
    class Outcome
      def initialize(patch:, status:, detail:)
        @patch = patch
        @status = status
        @detail = detail
      end

      attr_reader :patch, :status, :detail

      def ok?
        @status == :ok
      end

      def deferred?
        @status == :deferred
      end

      def failed?
        @status == :failed
      end
    end

    DEFAULT_CACHE_DIR = File.expand_path("../../../.cache/tarballs", __dir__).freeze
    MAX_REDIRECTS = 5

    def initialize(versions:, selection:, cache_dir: DEFAULT_CACHE_DIR)
      @versions = versions
      @selection = selection
      @cache_dir = cache_dir
    end

    # Full pipeline for one coherent build scenario (platform + pass):
    # returns the path of the patched tree (<outdir>/tfs-ruby-<version>-src).
    def prepare(version_name, outdir, platform:, pass:)
      entry = @versions.fetch(version_name)
      src = File.join(outdir, entry.src_tree_name)
      FileUtils.rm_rf(src)
      FileUtils.mv(pristine_tree(version_name, outdir), src)
      @selection.for(version_name, platform: platform, pass: pass).each do |patch|
        apply(src, patch, version_name, [])
      end
      src
    end

    # git apply --check of every selected patch against the pristine tree.
    # Returns the names of the patches that apply cleanly.
    def check(version_name, outdir)
      audit(version_name, outdir).filter_map do |outcome|
        raise ApplyError, outcome.detail if outcome.failed?

        outcome.patch.name if outcome.ok?
      end
    end

    # Per-patch check outcomes against the pristine tree: each selected
    # patch (or an explicitly given set) is tried with git apply --check
    # and reported :ok, :deferred (target absent pre-configure) or
    # :failed, without raising. Used by the release monitor.
    def audit(version_name, outdir, patches: nil)
      tree = pristine_tree(version_name, outdir)
      (patches || @selection.for(version_name)).map do |patch|
        begin
          applied = apply(tree, patch, version_name, ["--check"])
          Outcome.new(patch: patch, status: applied ? :ok : :deferred, detail: nil)
        rescue ApplyError => e
          Outcome.new(patch: patch, status: :failed, detail: e.message)
        end
      end
    end

    # Downloads a tarball URL into the cache (no-op when already cached)
    # and returns [path, sha256]. No manifest verification: used to pin
    # the sha256 of a NEW official release before it enters versions.yml.
    def fetch_tarball(url, file_name)
      FileUtils.mkdir_p(@cache_dir)
      dest = File.join(@cache_dir, file_name)
      download_to(url, dest) unless File.file?(dest)
      [dest, sha256(dest)]
    end

    # Fetch + verify + extract only: returns <outdir>/ruby-<version>.
    def pristine_tree(version_name, outdir)
      entry = @versions.fetch(version_name)
      tree = File.join(outdir, "ruby-#{entry.name}")
      FileUtils.rm_rf(tree)
      FileUtils.mkdir_p(outdir)
      extract(verified_tarball(entry), outdir)
      raise Error, "#{entry.name}: tarball did not contain ruby-#{entry.name}/" unless File.directory?(tree)

      tree
    end

    private

    def apply(tree, patch, version_name, extra_args)
      unless File.exist?(File.join(tree, patch.target_file))
        defer(version_name, patch)
        return false
      end

      _out, err, status = Open3.capture3(apply_env(tree), "git", "apply", *extra_args, patch.path, chdir: tree)
      return true if status.success?

      raise ApplyError, "FAIL #{version_name} #{patch.name}\n#{err.strip}"
    end

    # git apply run inside an enclosing git work tree (CI builds under
    # $GITHUB_WORKSPACE) resolves patch paths against that repository's
    # root and silently SKIPS every target -- exit 0, tree untouched.
    # Ceiling discovery at the output directory so git never sees a repo.
    def apply_env(tree)
      { "GIT_CEILING_DIRECTORIES" => File.realpath(File.dirname(tree)) }
    end

    def defer(version_name, patch)
      warn "DEFER #{version_name} #{patch.name} (target #{patch.target_file} not in pristine tree; apply after configure)"
      false
    end

    def verified_tarball(entry)
      FileUtils.mkdir_p(@cache_dir)
      tarball = File.join(@cache_dir, entry.tarball_name)
      return tarball if File.file?(tarball) && sha256(tarball) == entry.sha256

      FileUtils.rm_f(tarball)
      download_to(entry.url, tarball)
      return tarball if sha256(tarball) == entry.sha256

      raise IntegrityError, "#{entry.name}: sha256 mismatch for #{entry.tarball_name} from #{entry.url}"
    end

    def download_to(url, dest)
      uri = URI.parse(url)
      MAX_REDIRECTS.times do
        Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == "https") do |http|
          http.request(Net::HTTP::Get.new(uri)) do |response|
            case response
            when Net::HTTPSuccess
              File.open("#{dest}.tmp", "wb") { |file| response.read_body { |chunk| file.write(chunk) } }
              FileUtils.mv("#{dest}.tmp", dest)
              return
            when Net::HTTPRedirection
              uri = URI.parse(response.fetch("location"))
            else
              raise DownloadError, "HTTP #{response.code} from #{uri}"
            end
          end
        end
      end
      raise DownloadError, "too many redirects from #{url}"
    rescue SystemCallError, SocketError, Timeout::Error => e
      raise DownloadError, "cannot download #{uri}: #{e.message}"
    end

    def extract(tarball, outdir)
      _out, err, status = Open3.capture3("tar", "-xzf", tarball, "-C", outdir)
      raise Error, "tar failed on #{tarball}: #{err.strip}" unless status.success?
    end

    def sha256(path)
      Digest::SHA256.file(path).hexdigest
    end
  end
end
