# frozen_string_literal: true

require "digest"
require "fileutils"
require "net/http"
require "open3"
require "uri"

module Tfs
  # Prepares patched ruby source trees ("tfs-ruby-<version>-src"):
  # fetch the official tarball (sha256-verified, cached), extract it,
  # then apply the version's patch set with git apply.
  #
  # A selected patch whose target file does not exist in the pristine tree
  # (e.g. config.status, which is generated by ./configure) is DEFERRED
  # with a note on stderr -- the consumer applies it after configure.
  # Any other patch that fails to apply raises ApplyError (loud, named).
  class SourcePrep
    # Base error for every failure raised by SourcePrep.
    class Error < StandardError; end
    # Tarball bytes do not match the manifest sha256.
    class IntegrityError < Error; end
    # Tarball could not be downloaded.
    class DownloadError < Error; end
    # A patch failed git apply / git apply --check.
    class ApplyError < Error; end

    DEFAULT_CACHE_DIR = File.expand_path("../../../.cache/tarballs", __dir__).freeze
    MAX_REDIRECTS = 5

    def initialize(versions:, selection:, cache_dir: DEFAULT_CACHE_DIR)
      @versions = versions
      @selection = selection
      @cache_dir = cache_dir
    end

    # Full pipeline for one coherent build scenario (platform + pass):
    # returns the path of the patched tree (<outdir>/tfs-ruby-<version>-src).
    def prepare(version_name, outdir, platform:, pass:)
      entry = @versions.fetch(version_name)
      src = File.join(outdir, entry.src_tree_name)
      FileUtils.rm_rf(src)
      FileUtils.mv(pristine_tree(version_name, outdir), src)
      @selection.for(version_name, platform: platform, pass: pass).each do |patch|
        apply(src, patch, version_name, [])
      end
      src
    end

    # git apply --check of every selected patch against the pristine tree.
    # Returns the names of the patches that apply cleanly.
    def check(version_name, outdir)
      tree = pristine_tree(version_name, outdir)
      @selection.for(version_name).filter_map do |patch|
        patch.name if apply(tree, patch, version_name, ["--check"])
      end
    end

    # Fetch + verify + extract only: returns <outdir>/ruby-<version>.
    def pristine_tree(version_name, outdir)
      entry = @versions.fetch(version_name)
      tree = File.join(outdir, "ruby-#{entry.name}")
      FileUtils.rm_rf(tree)
      FileUtils.mkdir_p(outdir)
      extract(verified_tarball(entry), outdir)
      raise Error, "#{entry.name}: tarball did not contain ruby-#{entry.name}/" unless File.directory?(tree)

      tree
    end

    private

    def apply(tree, patch, version_name, extra_args)
      unless File.exist?(File.join(tree, patch.target_file))
        defer(version_name, patch)
        return false
      end

      _out, err, status = Open3.capture3("git", "apply", *extra_args, patch.path, chdir: tree)
      return true if status.success?

      raise ApplyError, "FAIL #{version_name} #{patch.name}\n#{err.strip}"
    end

    def defer(version_name, patch)
      warn "DEFER #{version_name} #{patch.name} (target #{patch.target_file} not in pristine tree; apply after configure)"
      false
    end

    def verified_tarball(entry)
      FileUtils.mkdir_p(@cache_dir)
      tarball = File.join(@cache_dir, entry.tarball_name)
      return tarball if File.file?(tarball) && sha256(tarball) == entry.sha256

      FileUtils.rm_f(tarball)
      download(entry, tarball)
      return tarball if sha256(tarball) == entry.sha256

      raise IntegrityError, "#{entry.name}: sha256 mismatch for #{entry.tarball_name} from #{entry.url}"
    end

    def download(entry, dest)
      uri = URI.parse(entry.url)
      MAX_REDIRECTS.times do
        Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == "https") do |http|
          http.request(Net::HTTP::Get.new(uri)) do |response|
            case response
            when Net::HTTPSuccess
              File.open("#{dest}.tmp", "wb") { |file| response.read_body { |chunk| file.write(chunk) } }
              FileUtils.mv("#{dest}.tmp", dest)
              return
            when Net::HTTPRedirection
              uri = URI.parse(response.fetch("location"))
            else
              raise DownloadError, "#{entry.name}: HTTP #{response.code} from #{uri}"
            end
          end
        end
      end
      raise DownloadError, "#{entry.name}: too many redirects from #{entry.url}"
    rescue SystemCallError, SocketError, Timeout::Error => e
      raise DownloadError, "#{entry.name}: cannot download #{uri}: #{e.message}"
    end

    def extract(tarball, outdir)
      _out, err, status = Open3.capture3("tar", "-xzf", tarball, "-C", outdir)
      raise Error, "tar failed on #{tarball}: #{err.strip}" unless status.success?
    end

    def sha256(path)
      Digest::SHA256.file(path).hexdigest
    end
  end
end
