#!/usr/bin/env python3
"""ar-rebuild.py — positional extract/rebuild for an ar archive that GNU
ar's rewriter mangles. Extracts every member to a directory with
position-unique names, then rebuilds a fresh GNU archive in the ORIGINAL
member order. Members named in <replace-dir> (by original member name)
are swapped for the replacement file contents.

Usage: ar-rebuild.py <in.a> <out.a> [replace-dir]"""

import os
import shutil
import struct
import subprocess
import sys


def parse(data):
    assert data[:8] == b"!<arch>\n", "not an ar archive"
    members = []  # (name, bytes)
    strtab = b""
    off = 8
    while off < len(data):
        raw_name = data[off:off + 16].decode("ascii", "replace")
        size = int(data[off + 48:off + 58].decode("ascii").strip())
        body_off = off + 60
        body = data[body_off:body_off + size]
        off = body_off + size + (size & 1)
        field = raw_name.strip()
        if field == "/":
            continue  # symbol table — regenerated by ranlib
        if field == "//":
            strtab = body
            continue
        if field.startswith("/") and field[1:].isdigit():
            start = int(field[1:])
            end = strtab.index(b"\n", start)
            name = strtab[start:end].decode("ascii", "replace").rstrip("/")
        else:
            name = field.rstrip("/").strip()
        members.append((name, body))
    return members


def main():
    src, dst = sys.argv[1], sys.argv[2]
    replace_dir = sys.argv[3] if len(sys.argv) > 3 else None
    with open(src, "rb") as f:
        members = parse(f.read())

    tmp = "/tmp/ar-rebuild-work"
    shutil.rmtree(tmp, ignore_errors=True)
    os.makedirs(tmp)
    seen = {}
    files = []
    replaced = []
    for i, (name, body) in enumerate(members):
        seen[name] = seen.get(name, 0) + 1
        fname = f"{i:05d}-{name.replace('/', '_')}"
        path = os.path.join(tmp, fname)
        if replace_dir and os.path.exists(os.path.join(replace_dir, name)):
            with open(os.path.join(replace_dir, name), "rb") as f:
                body = f.read()
            replaced.append(name)
        with open(path, "wb") as f:
            f.write(body)
        files.append(path)

    if os.path.exists(dst):
        os.remove(dst)
    # GNU ar keys members by basename; the position-prefixed names would
    # leak into the member table, so archive through basename-preserved
    # hardlinks in per-member dirs is overkill — GNU ar stores the name
    # as given on the command line (basename). Use a manifest pass.
    subprocess.run(["llvm-ar-18", "rcs", dst] + files, check=True)
    return members, replaced, dst


if __name__ == "__main__":
    members, replaced, dst = main()
    print(f"members: {len(members)}, replaced: {replaced}")
    out = subprocess.run(["llvm-ar-18", "t", dst], capture_output=True, text=True).stdout.splitlines()
    print(f"out members: {len(out)}")
